# Site settings
author: Jake
title: Life and Times of a New Programmer
header-img: img/home-bg.png
email: jake098877@gmail.com
copyright_name: Jake
description: > # this means to ignore newlines until "baseurl:"
  Subtitling the subtitle
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jake0988

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
